# NeRF-In Configuration File - Paper Compliant

model:
  # NeRF architecture (standard)
  pos_embed_dim: 10
  dir_embed_dim: 4
  net_depth: 8
  net_width: 256
  skip_layers: [4]
  
  # NeRF-In specific settings
  use_rgbd_prior: true
  use_fine_network: true
  use_importance_sampling: true
  
  # Sampling (following paper)
  num_samples_coarse: 64
  num_samples_fine: 128
  near_plane: 0.1
  far_plane: 10.0

training:
  # Two-stage training following paper
  pretraining_steps: 200000  # Stage 1: Standard NeRF training
  inpainting_steps: 50000    # Stage 2: NeRF-In optimization
  
  # Batch settings
  batch_size: 1024
  learning_rate: 0.0005
  
  # Loss weights following paper
  rgb_weight: 1.0    # Weight for color-guiding loss
  depth_weight: 0.1  # Weight for depth-guiding loss

# NeRF-In specific components
inpainting:
  # Mask transfer (STCN)
  stcn_model_path: null  # Path to STCN weights
  
  # RGB inpainting (MST/LaMa)
  inpaint_model: "lama"  # "mst" or "lama"
  
  # Bilateral solver parameters
  bilateral_sigma_spatial: 8.0
  bilateral_sigma_luma: 8.0
  bilateral_sigma_chroma: 8.0
  
  # View sampling (following paper)
  num_sampled_views: 24  # K camera positions along trajectory
  trajectory_type: "llff"  # LLFF-style trajectory

data:
  data_path: "data/sample_data"
  image_height: 480
  image_width: 640
  
  # Camera parameters
  near_plane: 0.1
  far_plane: 10.0

# System settings
device: null  # Auto-detect
num_workers: 4
log_dir: "logs"
checkpoint_dir: "checkpoints"
results_dir: "results"
